- name: Update package cache (Debian/Ubuntu)
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install prerequisites (Debian/Ubuntu)
  apt:
    name: "{{ debian_prerequisites }}"
    state: present
