---
- name: Get latest kubectl version
  uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: yes
  register: kubectl_latest_version
  when: kubectl_version == "latest"

- name: Set kubectl version variable
  set_fact:
    kubectl_install_version: "{{ kubectl_latest_version.content.strip() if kubectl_version == 'latest' else kubectl_version }}"

- name: Download kubectl binary
  get_url:
    url: "https://dl.k8s.io/release/{{ kubectl_install_version }}/bin/linux/amd64/kubectl"
    dest: /tmp/kubectl
    mode: '0755'

- name: Install kubectl
  copy:
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    remote_src: yes

- name: Install Helm
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
